export const actionTypes = {
    FETCH_CATEGORIES : 'FETCH_CATEGORIES',
    FETCH_CATEGORY_ITEMS: 'FETCH_CATEGORY_ITEMS',
    ADD_TO_SELECTED_ITEMS: 'ADD_TO_SELECTED_ITEMS',
    CALCULATE_AVERAGE_COST: 'CALCULATE_AVERAGE_COST',
}